Adapter master data helm chart
misdwss/iFix-DevOps pull request #270
Opened 2022-02-21 09:51 UTC by pintu-eGov

2022-02-21 11:57 UTC, rushang7-eGov requested changes

2022-02-21 11:57 UTC, rushang7-eGov commented on deploy-as-code/helm/charts/ifix-services/adapter-master-data-service/templates/ingress.yaml
> +{{- template "common.ingress" . -}}
We need ingress only when there are api calls coming from outside the kube cluster.

2022-02-21 11:57 UTC, rushang7-eGov commented on deploy-as-code/helm/charts/ifix-services/adapter-master-data-service/values.yaml
> +  zuul: false
When zuul is marked false, the api call from outside will directly reach the server. So standard protections like, Authn&AuthZ, Rate Limiting, etc. will get skipped, due to which there are chances of an attack.

2022-02-21 11:57 UTC, rushang7-eGov commented on deploy-as-code/helm/charts/ifix-services/adapter-master-data-service/values.yaml
> +  livenessProbePath: "/adapter-master-data/health"
Are these endpoints present in the service?

2022-02-21 11:57 UTC, rushang7-eGov commented on deploy-as-code/helm/environments/mgramseva-qa-secrets.yaml
> +            mongo-db-username: ENC[AES256_GCM,data:jCYkLFcbNZwy9A==,iv:QKp+PAh6snZ8gDJZ1KhdLb210PsL0N1dTdzJUCkbl0s=,tag:p4cKNgJuavzLNu6giQmtRA==,type:str]
The secrets can't be copied by simple copy-paste. They have signature associated with them(present at the end of the file). You need to request DevOps team to copy them.

2022-02-21 11:57 UTC, rushang7-eGov commented on deploy-as-code/helm/charts/ifix-services/adapter-master-data-service/values.yaml
> +        key: adapter-department-entity-service
We will let the name be ifix-department-entity-service.

2022-02-21 11:57 UTC, rushang7-eGov commented on deploy-as-code/helm/charts/ifix-services/adapter-master-data-service/values.yaml
> +
namespace key is missing.

2022-02-23 06:43 UTC, rushang7-eGov approved these changes

2022-03-02 06:28 UTC, rushang7-eGov approved these changes

2022-03-02 06:33 UTC, sathishp-eGov approved these changes

2022-03-02 06:33 UTC, merged